baseURL = "https://teebor-choka.github.io/"
languageCode = "en-UA"
defaultContentLanguage = "en"
title = "Teebor's musings"
theme = "CodeIT"
disqusShortname = "teeborchoka"
publishDir = "./public"

[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4

# LoveIt theme settings
# -> https://hugoloveit.com/theme-documentation-basics/#site-configuration
[params]
    version = "0.2.X"
    keywords = ["tech", "philosophy", "ML", "AI", "DevOps", "Computer Science", "Computer Vision"]
    defaultTheme = "auto"       # light|dark|auto
	description = "Exploring a technical mind."

  [params.app]
    noFavicon = false
    svgFavicon = ""
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = "search phrase"
    maxResultLength = 20
    snippetLength = 30
    highlightTag = "em"
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      pre = ""
      name = "Tibor's musings"
      post = ""

  # Footer config
  [params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2020
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/avatar.jpeg"
      subtitle = ""
      typeit = true
      social = true
      disclaimer = "Hit me up if you have something to say..."
    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    GitHub = "Teebor-Choka"
    Linkedin = "tibor-csóka"
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Email = "csokat+Teebor-Choka.github.io@gmail.com"
    RSS = true

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true

    [params.page.toc]
      enable = true
      auto = true
    [params.page.math]
      enable = true
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      copyTex = true
      mhchem = true

    [params.page.code]
      copy = true
      maxShownLines = 25

    [params.page.mapbox]
      accessToken = ""
      lightStyle = "mapbox://styles/mapbox/light-v9"
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      HackerNews = true
      Reddit = true
      Pinterest = false
      Tumblr = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false

    [params.page.comment]
      enable = true
      [params.page.comment.disqus]
        enable = true
        shortname = "teeborchoka"
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      [params.page.comment.commento]
        enable = false
    [params.page.seo]
      [params.page.seo.publisher]
        name = "xxxx"
        [params.page.seo.publisher.logo]
          url = "logo.png"
          width = 127
          height = 40
      [params.page.seo.logo]
        url = "logo.png"
        width = 127
        height = 40
      [params.page.seo.image]
        url = "cover.png"
        width = 800
        height = 600

[params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  [params.analytics]
    enable = false
    [params.analytics.google]
      id = "UA-166642225-1"
      anonymizeIP = true
      cookie = false
    [params.analytics.fathom]
      id = ""
      server = ""

  [params.cdn]
    normalizeCSS = ""
    fontawesomeFreeCSS = ""
    simpleIconsPrefix = ""
    # animate.css@3.7.2 https://github.com/daneden/animate.css
    animateCSS = ""
    # smooth-scroll@16.1.3
    smoothScrollJS = ""
    # LoveIt NEW | 0.2.0 autocomplete.js@0.37.1
    autocompleteJS = ""
    # LoveIt NEW | 0.2.0 lunr.js@2.3.8
    lunrJS = ""
    # LoveIt NEW | 0.2.0 algoliasearch@4.2.0
    algoliasearchJS = ""
    # lazysizes@5.2.0
    lazysizesJS = ""
    # LoveIt NEW | 0.2.3 object-fit-images@3.2.4
    objectFitImagesJS = ""
    # LoveIt NEW | 0.2.0 twemoji@12.1.5
    twemojiJS = ""
    # lightgallery.js@1.1.3
    # lg-thumbnail.js@1.1.0
    # lg-zoom.js@1.0.1
    lightgalleryCSS = ""
    lightgalleryJS = ""
    lightgalleryThumbnailJS = ""
    lightgalleryZoomJS = ""
    # LoveIt NEW | 0.2.0 clipboard.js@2.0.6
    clipboardJS = ""
    # sharer.js@0.4.0
    sharerJS = ""
    # typeit@6.5.1
    typeitJS = ""
    # katex@0.11.1
    katexCSS = ""
    katexJS = ""
    katexAutoRenderJS = ""
    katexCopyTexCSS = ""
    katexCopyTexJS = ""
    katexMhchemJS = ""
    # mermaid@8.5.0
    mermaidJS = ""
    # echarts@4.7.0
    echartsJS = ""
    echartsMacaronsJS = ""
    # LoveIt NEW | 0.2.0 mapbox-gl@1.10.0
    mapboxGLCSS = ""
    mapboxGLJS = ""
    # aplayer@1.10.1
    aplayerCSS = ""
    aplayerJS = ""
    # meting@2.0.1
    metingJS = ""
    # gitalk@1.6.2
    gitalkCSS = ""
    gitalkJS = ""
    # valine@1.4.14
    valineJS = ""

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[author]
  name = "Tibor Csóka"
  email = "csokat+Teebor-Choka.github.io@gmail.com"
  link = ""

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
